### ISSUE TITLE
[2020-10-16] 코드숨 결제 기능 개발

### ISSUE THREAD

**Issue by hannut91** [daadaadaah/online-mogagko#4]
## 오늘 모각코에서 무엇을 하셨나요?
* 코드숨 클라이언트에서 결제 요청을 했을 때 `oderId`를 생성하고, BootPay로 검증요청을 하는 것까지 하겠습니다

## 하면서 무엇을 느끼셨나요?

* 지각하면 안된다

**Comment by daadaadaah** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ아주 좋은 회고네요ㅎㅎㅎ
